jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master

language: node_js

node_js:
  - 'stable'

services:
  - mongodb

script: 
  - cd backend
  - npm install
  - cd utils
  - npm install
  - cd ../unitTests/userModuleNoMockDB
  - npm install
  - npm run test
  - cd ../healthStatusModuleNoMockDB
  - npm install
  - npm run test
  - npm install
  - cd ../../integrationTests
  - npm run test


 