language: node_js

node_js:
  - 'stable'

services:
  - mongodb
  - mongooose

script: 
  - cd backend/tests
  - npm run test

jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master
 