jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master

language: node_js

node_js:
  - 'stable'

services:
  - mongodb

script: 
  - cd backend/unitTests/userModuleNoMockDB
  - npm run test
  - cd ../healthStatusModuleNoMockDB
  - npm run test
  - cd ../../integrationTests
  - npm run test


 